In [1]:
import tensorflow as tf

## Rank

### Rank 0

In [2]:
mammal = tf.Variable('Elephant', tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

### Rank 1

In [3]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

### Higher ranks

In [4]:
mycat = tf.Variable([[7], [11]], tf.int16)
myxor = tf.Variable([[False, True], [True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7], [11]], tf.int32)

In [5]:
my_image = tf.zeros([10, 299, 299, 3])

### Getting a `tf.Tensor` object's rank

In [6]:
r = tf.rank(my_image)
sess = tf.Session()
sess.run(r)

4

### Referring to `tf.Tensor` slices

In [7]:
# For a rank 1 tensor
my_scalar = first_primes[2]
init = tf.global_variables_initializer()
sess.run(init)
sess.run(my_scalar)

5

In [8]:
# For tensors of rank 2 or higher
my_scalar = squarish_squares[0, 1]
sess.run(my_scalar)

9

In [9]:
my_row_vector = squarish_squares[1]
sess.run(my_row_vector)

array([16, 25], dtype=int32)

In [10]:
my_column_vector = squarish_squares[ : , 1]
sess.run(my_column_vector)

array([ 9, 25], dtype=int32)

## Shape

|<div align="left">Rank</div>|<div align="left">Shape</div>|<div align="left">Dimension number</div>|<div align="left">Example</div>|
|-|-|-|-|
|<div align="left">0</div>|<div align="left">[]</div>|<div align="center">0-D</div>|<div align="left">scalar</div>|
|<div align="left">1</div>|<div align="left">[D0]</div>|<div align="center">1-D</div>|<div align="left">shape[5]</div>|
|<div align="left">2</div>|<div align="left">[D0,D1]</div>|<div align="center">2-D</div>|<div align="left">shape[3,4]</div>|
|<div align="left">3</div>|<div align="left">[D0,D1,D2]</div>|<div align="center">3-D</div>|<div align="left">shape[1,4,3]</div>|
|<div align="left">n</div>|<div align="left">[D0,D1,...Dn-1]</div>|<div align="center">n-D</div>|<div align="left">shape[D0,D1,...Dn-1]</div>|

### Getting a `tf.Tensor` object's shape

In [11]:
zeros = tf.zeros(squarish_squares.shape[1])
sess.run(zeros)

array([0., 0.], dtype=float32)

### Changing the shape of a `tf.Tensor`

In [12]:
rank_three_tensor = tf.ones([3, 4, 5])
# Reshape existing content into a 6*10 matrix
matrix = tf.reshape(rank_three_tensor, [6, 10])
# Reshape existing content into a 3x20 matrix.
# -1 tells reshape to calculate the size of this dimension.
matrixB = tf.reshape(matrix, [3, -1])
# Reshape existing content into a 4x3x5 tensor
matrixAlt = tf.reshape(matrixB, [4, 3, -1])

## Data types

In [13]:
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)

## Evaluating Tensors

In [14]:
constant = tf.constant([1, 2, 3])
tensor = constant * constant
sess.run(tensor)

array([1, 4, 9], dtype=int32)

In [15]:
p = tf.placeholder(tf.float32)
t = p + 1.0
sess.run(t, feed_dict={p:2.0})

3.0